owners:
    Hanger:
        locations:
            - brewersgrill
        colors:
            evenbg: 'd5d3d5'
            evenfg: '000000'
            oddbg: 'a77380'
            oddfg: 'ffffff'
            headerbg: '6b303f'
            headerfg: 'ffffff'
            footerbg: '6b303f'
            footerfg: 'ffffff'
        prices:
            name: Prices
            items:
                - pint
