owners:
    Hanger:
        locations:
            - brewersgrill
        colors:
            evenbg: 'F4FCBB'
            evenfg: '000000'
            oddbg: 'c7ffa0'
            oddfg: '000000'
            headerbg: 'BF162C'
            headerfg: 'ffffff'
            footerbg: 'BF162C'
            footerfg: '000000'
        prices:
            name: Prices
            items:
                - pint
