owners:
    Hanger:
        locations:
            - brewersgrill
        colors:
            evenbg: 'd5d3d5'
            evenfg: '000000'
            oddbg: '800080'
            oddfg: 'ffffff'
            headerbg: '800080'
            headerfg: 'ffffff'
            footerbg: '800080'
            footerfg: 'ffffff'
        prices:
            name: Prices
            items:
                - pint
